interShoptrace/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('links:type-link-add'))),
    path('link/', include(('links.urls', 'links'), namespace='links')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/', include('allauth.urls')),
]

links/urls.py
from django.urls import path
from links import views

urlpatterns = [
    path('', views.AllLinkListView.as_view(), name='all-link-list'),
    path('type/', views.TypeLinkListView.as_view(), name='type-link-list'),
    path('type-history/', views.TypeLinkHistoryListView.as_view(), name='type-link-history-list'),
    path('type-history/<int:pk>/', views.TypeLinkHistoryDetailView.as_view(), name='type-link-history-detail'),
    path('type/<int:pk>/', views.ProductListView.as_view(), name='type-link-product-list'),
    path('product/<int:pk>/', views.InventoryListView.as_view(), name='type-link-inventory-list'),
    path('period/', views.PeriodLinkListView.as_view(), name='period-link-list'),
    path('period/<int:pk>/', views.ProductListView.as_view(), name='period-link-product-list'),
    path('insert/', views.LinkInsertView.as_view(), name='type-link-add'),
    path('fetch/', views.GetPeriodLinkView.as_view(), name='period-link-add'),
    path('scheduler-record/', views.SchedulerRecordListView.as_view(), name='scheduler-record-list'),
    path('scheduler-record/<int:pk>/', views.SchedulerRecordDetailView.as_view(), name='scheduler-record-detail'),
    path('scraper-record/', views.ScraperRecordListView.as_view(), name='scraper-record-list'),
    path('moving-product/', views.MovingProductListView.as_view(), name='moving-product-list'),
    path('commafeed/', views.CommaFeedListView.as_view(), name='commafeed-list'),

    path('best-product/', views.BestProductRecordListView.as_view(), name='best-product-record-list'),
    path('best-product/<int:pk>', views.BestProductRecordDetailView.as_view(), name='best-product-detail'),
    
    path('product/', views.ProductInventory)
]

templates/base.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dataTables.semanticui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/blue.css' %}">
    {% block extra_css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <main role="main" class="container">
        {% block content %}
        {% endblock %}
    </main>
    
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.semanticui.min.js' %}"></script>
    <script src="{% static 'js/semantic.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script src="{% static 'js/icheck.min.js' %}"></script>
    <script src="{% static 'js/d3.v4.min.js' %}"></script>
    
    {% block extra_js %}
    {% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}
{% load static notifications_tags %}

<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>

<script>
    function custom_notification_list(data) {
        var menus = document.getElementsByClassName(notify_menu_class);
        if (menus) {
            var messages = data.unread_list.map(function (item) {
                var message = "";
                if(typeof item.verb !== 'undefined'){
                    message = message + " " + item.verb;
                }
                if(typeof item.target !== 'undefined'){
                    message = message + " " + item.target;
                }
                return '<li>' + message + '</li>';
            }).join('')

            for (var i = 0; i < menus.length; i++){
                menus[i].innerHTML = messages;
            }
        }
    }
</script>
{% register_notify_callbacks callbacks='fill_notification_badge,custom_notification_list' fetch=20 refresh_period=5 badge_class='badge badge-secondary' %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href=""><h2>Internal Shoptrace</h2></a>
        {% if request.user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">@</span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">            
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'links:all-link-list' %}">All Links<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="manualNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manual</a>
                        <div class="dropdown-menu" aria-labelledby="manualNavbarDropdown">
                            <a class="dropdown-item" href="{% url 'links:type-link-add' %}">Add Link</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:type-link-history-list' %}">Add Link History</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:type-link-list' %}">Added Links</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="insightsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Insights</a>
                        <div class="dropdown-menu" aria-labelledby="insightsDropdown">
                            <a class="dropdown-item" href="{% url 'links:scraper-record-list' %}">Scraper Results</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:moving-product-list' %}">Moving Products</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:best-product-record-list' %}">Best Products</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="externalDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">External Data Integration</a>
                        <div class="dropdown-menu" aria-labelledby="externalDropdown">
                            <a class="dropdown-item" href="{% url 'links:period-link-add' %}">Firebase Fetch</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:period-link-list' %}">Firebase Fetched Links</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'links:commafeed-list' %}">CommaFeed</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'links:scheduler-record-list' %}">Scheduler Records</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn" type="button" id="notificationButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                notifications {% live_notify_badge badge_class='badge badge-secondary' %}
                            </button>
                            <div class="dropdown-menu notification-content" aria-labelledby="notificationButton">
                                <a href="{% url 'notifications:unread' %}">
                                    {% live_notify_list %}
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/accounts/logout/" class="nav-link">Log out</a>
                    </li>
                </ul>
            </div>
        {% else %}
        <ul class="navbar-nav">
            <li>
                <a href="/accounts/login/" class="nav-link">Login</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>